### ISSUE TITLE
use lib "$Bin/../lib"; ???

### ISSUE THREAD

**Issue by ptakopysk** [udapi/udapi-perl#1]
Hi,
not sure what this line is for: https://github.com/udapi/udapi-perl/blob/master/script/udapi.pl#L5
`use lib "$Bin/../lib";`
But, at least on UFAL machines with perlbrew, it leads to the following error when trying to run udapi:
`Getopt::Long version 2.43 required--this is only version 2.39 at /ha/work/projects/perlbrew/Ubuntu/14.04/x86_64/perls/perl-5.18.2/bin/../lib/5.18.2/Getopt/Long.pm line 1489.
BEGIN failed--compilation aborted at /net/work/projects/perlbrew/Ubuntu/14.04/x86_64/perls/perl-5.18.2/lib/site_perl/5.18.2/MooX/Options/Descriptive.pm line 18.
Compilation failed in require at /net/work/projects/perlbrew/Ubuntu/14.04/x86_64/perls/perl-5.18.2/lib/site_perl/5.18.2/MooX/Options/Role.pm line 18.
BEGIN failed--compilation aborted at /net/work/projects/perlbrew/Ubuntu/14.04/x86_64/perls/perl-5.18.2/lib/site_perl/5.18.2/MooX/Options/Role.pm line 18.
Compilation failed in require at /net/work/projects/perlbrew/Ubuntu/14.04/x86_64/perls/perl-5.18.2/lib/site_perl/5.18.2/Module/Runtime.pm line 317.
BEGIN failed--compilation aborted at /net/work/projects/perlbrew/Ubuntu/14.04/x86_64/perls/perl-5.18.2/lib/site_perl/5.18.2/Udapi/Core/Run.pm line 6.
Compilation failed in require at /net/work/projects/perlbrew/Ubuntu/14.04/x86_64/perls/perl-5.18.2/bin/udapi.pl line 6.
BEGIN failed--compilation aborted at /net/work/projects/perlbrew/Ubuntu/14.04/x86_64/perls/perl-5.18.2/bin/udapi.pl line 6.`

It seems that the line makes udapi look for libraries in a wrong directory, so even though both `cpanm` and `whichpm` say that my `Getopt::Long` is up to date (version 2.48), udapi finds a wrong version of the library and then complains about it and dies.

Interestingly, when I simply commented it out, udapi started working properly for me...

**Comment by ptakopysk** [comment]
Note: I used the cpanm&github installation, i.e. `cpanm git://github.com/udapi/udapi-perl`

**Comment by martinpopel** [comment]
OK, I deleted the line.  [INSTALL.md](https://github.com/udapi/udapi-perl/blob/master/INSTALL.md) suggests to add the directory to `export PERL5LIB="$HOME/udapi-perl/lib:$PERL5LIB"` in "developers" mode anyway (and in "user" mode it is not needed). I just wonder why we have two versions of Getopt::Long in our Perlbrew (but that's an unrelated issue).
